{{ if not .Values.sealedSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.namespace }}-ssh-private-key
  namespace: {{ .Values.cluster.namespace }}
data:
  ssh-privatekey: {{ .Values.secrets.sshPrivateKey | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cluster.namespace }}-aws-creds
  namespace: {{ .Values.cluster.namespace }}
data:
  aws_access_key_id: {{ .Values.secrets.aws_access_key_id | b64enc  }}
  aws_secret_access_key: {{ .Values.secrets.aws_secret_access_key | b64enc  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.namespace }}-pull-secret
  namespace: {{ .Values.cluster.namespace }}
data:
  .dockerconfigjson: {{ .Values.secrets.pullSecret | b64enc  }}
type: kubernetes.io/dockerconfigjson
{{ end }}