---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-install-config
  namespace: {{ .Values.cluster.name }}
stringData:
  install-config.yaml: |-
      apiVersion: v1
      metadata:
        name: {{ .Values.cluster.name }}
      baseDomain: {{ .Values.cluster.baseDomain }}
      controlPlane:
        name: master
        architecture: amd64
        hyperthreading: Enabled
        replicas: 1
        platform:
          aws:
            zones:
            - {{ .Values.cluster.region }}a
            rootVolume:
              iops: 4000
              size: 100
              type: io1
            type: m5.2xlarge
      compute:
        - name: worker
          hyperthreading: Enabled
          architecture: amd64
          replicas: 0
          platform:
            aws:
              rootVolume:
                iops: 2000
                size: 100
                type: io1
              type: m5.xlarge
      networking:
        networkType: OVNKubernetes
        clusterNetwork:
          - cidr: 10.128.0.0/14
            hostPrefix: 23
        machineNetwork:
          - cidr: 10.0.0.0/16
        serviceNetwork:
          - 172.30.0.0/16
      platform:
        aws:
          region: {{ .Values.cluster.region }}
      pullSecret: ''
      sshKey: {{ .Values.sshPubKey }}